# Generated by Django 3.0.5 on 2020-04-06 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_auto_20200406_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sequence',
            name='organism',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence_description',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence_name',
            field=models.CharField(max_length=300),
        ),
    ]
