# Generated by Django 3.1.1 on 2021-01-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210120_2346'),
    ]

    operations = [
        migrations.RunSQL(
            sql = '''
            CREATE TRIGGER sequence_update_trigger
            BEFORE INSERT OR UPDATE OF seq_acc, seq_name, seq_desc, seq_organism, seq_type, seq, search_vector
            ON pages_sequence
            FOR EACH ROW EXECUTE PROCEDURE
            tsvector_update_trigger(
                search_vector, 'pg_catalog.english', seq_acc, seq_name, seq_desc, seq_organism, seq_type, seq);
            
            UPDATE pages_sequence SET search_vector = NULL;
            ''',

            reverse_sql='''
            DROP TRIGGER IF EXISTS sequence_update_trigger
            ON pages_sequence;
            '''
        ),
    ]
