# Generated by Django 3.1.5 on 2021-01-21 22:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0005_create_trigger'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sequence',
            name='seq_organism',
        ),
        migrations.RemoveField(
            model_name='sequence',
            name='seq_type',
        ),
        migrations.CreateModel(
            name='Taxonomy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tax_organism', models.CharField(max_length=2000)),
                ('tax_ispathogen', models.CharField(max_length=50)),
                ('fk_seq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pages.sequence')),
            ],
        ),
        migrations.AddField(
            model_name='sequence',
            name='seq_tax',
            field=models.ManyToManyField(blank=True, to='pages.Taxonomy'),
        ),
    ]
