# Generated by Django 3.0.5 on 2020-04-05 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='sequence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accession_number', models.CharField(max_length=50)),
                ('sequence_name', models.CharField(max_length=50)),
                ('sequence_description', models.CharField(max_length=150)),
                ('organism', models.CharField(max_length=100)),
            ],
        ),
    ]
