# Generated by Django 3.0.5 on 2020-04-06 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequence',
            name='seq',
            field=models.CharField(default='ATCG', max_length=3000),
        ),
        migrations.AddField(
            model_name='sequence',
            name='sequence_type',
            field=models.CharField(default='RHIZO', max_length=50),
        ),
        migrations.AlterField(
            model_name='sequence',
            name='sequence_description',
            field=models.CharField(max_length=300),
        ),
    ]
