# Generated by Django 3.1.1 on 2021-01-20 23:46

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20200406_2214'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sequence',
            old_name='accession_number',
            new_name='seq_acc',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='sequence_description',
            new_name='seq_desc',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='sequence_name',
            new_name='seq_name',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='organism',
            new_name='seq_organism',
        ),
        migrations.RenameField(
            model_name='sequence',
            old_name='sequence_type',
            new_name='seq_type',
        ),
        migrations.AddField(
            model_name='sequence',
            name='search_vector',
            field=django.contrib.postgres.search.SearchVectorField(null=True),
        ),
        migrations.AddIndex(
            model_name='sequence',
            index=django.contrib.postgres.indexes.GinIndex(fields=['search_vector'], name='pages_seque_search__233eb4_gin'),
        ),
    ]
